app/lib/view/vertretungsplan/vertretungsplan.dart

Wenn man versucht den Vp zu laden crasht es.
Das liegt leider wegen der Unterschiede zwischen verschiedenen Schulportalen, da sie es ja so einfach machen wollen wie möglich.
Aber wenn gefixt funktioniert alles:

🐛 Vp view crashes wenn Art ist Null

---

app/android/app/build.gradle
app/lib/client/client.dart
app/lib/client/cryptor.dart
app/lib/main.dart
app/lib/view/settings/subsettings/supported_features.dart
app/pubspec.lock
app/pubspec.yaml

Reverts alessioC42/SPH-vertretungsplan#25
(lol)

Revert "Revert "Add encryption support.""

---

app/lib/client/client.dart
app/lib/view/conversations/conversations.dart

+ Added refreshing conversations via RefreshIndicator and StreamBuilder
+ Faster conversations via caching in variables.

Refreshing and faster conversations.

---

app/lib/client/client.dart
app/lib/view/calendar/calendar.dart

*Translate my https://github.com/kurwjan/LanisAPI/blob/master/src%2Flanisapi%2Ffunctions%2Fcalendar.py `get_responsible()` to Dart.*
*Getting the category is right now not possible because it's a number, thanks Lanis.*

Fix calendar

---

app/lib/client/client.dart
app/lib/main.dart
app/lib/view/conversations/conversations.dart
app/lib/view/conversations/detailed_conversation.dart
app/lib/view/settings/subsettings/user_login.dart
app/lib/view/settings/subsettings/userdata.dart
app/lib/view/vertretungsplan/vertretungsplan.dart

Some more bugs

---

app/lib/client/client.dart
app/lib/view/mein_unterricht/course_overview.dart
app/pubspec.lock
app/pubspec.yaml

Dateien werden Heruntergeladen und mit den Systemviewer geöffnet. 
Wenn eine Datei heruntergeladen wurde, muss sie nicht erneut heruntergeladen werden.

Mein unterricht document attachments

---

app/lib/main.dart

Fix: set aspect ratio of image to 16:9

---

README.md
app/lib/main.dart
app/lib/view/calendar/calendar.dart
app/lib/view/settings/subsettings/about.dart
bugreport/server/src/index.ts

fixes #46 
adds refresh indicator

Calendar fix

---

app/lib/view/mein_unterricht/course_overview.dart

fix "verspäted" detail rendered in wrong place.

---

app/lib/main.dart

sonst nach ersten login views sind leer

Prepare fetchers earlier

---

app/lib/client/client.dart
app/lib/view/calendar/calendar.dart
app/lib/view/conversations/conversations.dart
app/lib/view/mein_unterricht/course_overview.dart
app/lib/view/mein_unterricht/mein_unterricht.dart
app/lib/view/vertretungsplan/vertretungsplan.dart

Fixes login error when there is no network connection
Fixes "Mein Unterricht" detailed page to break when there is no network connection.

Fix no network login

---

app/lib/client/client.dart
app/lib/client/fetcher.dart

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: type 'int' is not a subtype of type 'Iterable<dynamic>'
at .filter(filterlogic.dart:37)
at Fetcher.fetchData.<fn>(fetcher.dart:56)

fix fetcher

---

app/lib/client/client.dart
app/lib/main.dart

fix login fetchers not initialized.

---

app/lib/client/client.dart
app/lib/shared/errorView.dart
app/lib/view/calendar/calendar.dart
app/lib/view/vertretungsplan/vertretungsplan.dart

_Teil von besserer UI/UX (#40)_

Calendar improvements

---

app/lib/client/client.dart
app/lib/main.dart

Disables "mein unterricht" for non-students

63 possible problems with teacher accounts

---

app/lib/background_service/service.dart

`combinedVPlan.add(plan);` => `combinedVPlan.addAll(plan);`

Fix notifications

---

app/lib/main.dart

add link to moodle login page

---

app/lib/client/client.dart
app/lib/main.dart
app/lib/themes.dart
app/lib/view/settings/subsettings/theme_changer.dart

Einfach nur kleiner refactor, damit es bissl besser ist.

Cleanup color theme code

---

app/lib/client/client.dart
app/lib/main.dart
app/lib/shared/whats-new/whats_new.dart
app/pubspec.lock
app/pubspec.yaml

Checks on app start, if own app version is different from the last one stored in globalStorage, the release notes are fetched from github and shown in a dialog.
Future release notes will contain more text so the user does not have to understand the auto-generated ones.

whats-new screen on app startup

---

app/lib/client/client.dart
app/lib/main.dart
app/lib/shared/whats-new/whats_new.dart
app/lib/shared/whats_new.dart
app/lib/view/conversations/detailed_conversation.dart
app/lib/view/vertretungsplan/vertretungsplan.dart

- Constrain Whats-New Alertdialog
- `GlobalKeys` können nicht in _vertretungsplan.dart_ `null` sein
- _(Ich hoffe das fixt den bug: "java.lang.Exception: Null check operator used on a null value" in Countly, schon als resolved markiert)_ 
- Fixe größere Länge an Widgets als es wirklich an widgets gibt in detailed conversations

Generelle (Hot-)fixes

---

app/lib/view/settings/subsettings/supported_features.dart

Add Nachrichten Beta-Version to supported apps.

---

app/lib/client/client.dart
app/lib/main.dart

Duplikate von "Mein Unterricht" mit unterschiedlicher Groß-/Kleinschreibung entfernen

---

app/lib/client/client.dart
app/lib/main.dart
app/lib/view/bug_report/send_bugreport.dart

Hinzufügen zusätzlicher Möglichkeit von nicht-beta Nachrichtenmodul

Nachrichten Beta / Release Parallel-Unterstützung

---

app/lib/view/vertretungsplan/vertretungsplan.dart

Habe Anfragen wegen dem Wochentag bekommen.

Feat: Add weekday and badge with count to substitutions tab

---

app/android/app/src/main/AndroidManifest.xml

https://lanis-mobile.duckdns.org/dashboard#/659c667be9bd1eab79ee33e0/crashes/6ffd358509a405675c6cb1822136e9efaa6a0677
https://pub.dev/packages/url_launcher#android
https://stackoverflow.com/questions/75690046/flutter-unhandled-exception-platformexceptionactivity-not-found-no-activity-f

Fix: url_launcher on special URI's

---

app/lib/client/client.dart

Durch regelmäßiges refresh logout verhindern (60 s)

Session verlängerungsanfragen

---

app/lib/client/client.dart

Neuer Parser für VPlan ohne JSON-API vom SPH

Vertretungsplan fix

---

app/lib/client/client.dart
app/lib/view/mein_unterricht/course_overview.dart
app/lib/view/mein_unterricht/mein_unterricht.dart

sort and filter "Aktuelles" on "Mein Unterricht"

---

app/lib/client/client.dart

TryCatch in preventLogout

---

app/lib/client/client.dart

Spaltenübergreifende Zeilen mit Info, dass keine Vertretungen vorliegen ausschließen

Fix VPlan wenn keine Einträge

---

app/lib/main.dart

Zur Analyse der Nutzer. Mich interessiert, wie viele von meiner Schule kommen und wie viele von anderen.

record school id for analytics

---

app/lib/background_service/service.dart
app/lib/client/client.dart
app/lib/client/storage.dart
app/lib/main.dart
app/lib/shared/whats_new.dart
app/lib/themes.dart
app/lib/view/login/auth.dart
app/lib/view/settings/subsettings/countly_analysis.dart
app/lib/view/settings/subsettings/load_mode.dart
app/lib/view/settings/subsettings/notifications.dart
app/lib/view/vertretungsplan/filterlogic.dart

Handle storage keys and defaults globaly

---

app/lib/background_service/service.dart
app/lib/client/client.dart
app/lib/client/fetcher.dart
app/lib/main.dart
app/lib/shared/errorView.dart
app/lib/view/calendar/calendar.dart
app/lib/view/conversations/conversations.dart
app/lib/view/conversations/detailed_conversation.dart
app/lib/view/mein_unterricht/course_overview.dart
app/lib/view/mein_unterricht/upload_page.dart
app/lib/view/vertretungsplan/vertretungsplan.dart

Negative Zahlen als Statuscodes weiter ersetzen
Bezogen auf #154

Exceptions verwenden

---

app/lib/client/client_submodules/mein_unterricht.dart
app/lib/view/mein_unterricht/course_overview.dart

Add button to show 1st halbjahr if possible

---

app/lib/shared/apps.dart
app/lib/view/settings/subsettings/supported_features.dart

Verbesserung der Code-Struktur von SPHAppEnum und Möglichkeit zusätzliche Unterstützungs-Optionen anzuzeigen (hier: `Geplant` und `in Arbeit`)

Modul-Enum optimieren und Support-Status erweitern

---

app/lib/client/client.dart
app/lib/client/client_submodules/conversations.dart
app/lib/client/client_submodules/mein_unterricht.dart
app/lib/view/mein_unterricht/mein_unterricht.dart
app/lib/view/mein_unterricht/upload_page.dart
app/lib/view/vertretungsplan/vertretungsplan.dart

Exceptions weiter

---

app/lib/client/client.dart
app/lib/client/client_submodules/calendar.dart
app/lib/client/client_submodules/conversations.dart
app/lib/client/client_submodules/mein_unterricht.dart
app/lib/client/client_submodules/substitutions.dart
app/lib/client/connection_checker.dart
app/lib/client/fetcher.dart
app/lib/main.dart
app/lib/shared/exceptions/client_status_exceptions.dart
app/lib/shared/shared_functions.dart
app/pubspec.lock
app/pubspec.yaml

fixes #158
@CodeSpoof du müsstest das warscheinlich nochmal in deiner Schule testen.

sph connection check

---

app/lib/client/client.dart

https://lanis-mobile.duckdns.org/dashboard#/659c667be9bd1eab79ee33e0/crashes/8b17b553e731ae18950ed8347fa73db7c4de4742

Fehler wenn session nicht vorhanden

---

app/lib/home_page.dart

https://lanis-mobile.duckdns.org/dashboard#/659c667be9bd1eab79ee33e0/crashes/bc2e544501a9f97eaa963150f007dfdb1e8725d2

'selectedDestinationDrawer' has not been initialized

---

app/lib/client/client_submodules/mein_unterricht.dart
app/lib/view/mein_unterricht/course_overview.dart

Feat: Show comments on Marks

---

app/lib/client/client.dart
app/lib/shared/exceptions/client_status_exceptions.dart
app/lib/startup.dart
app/lib/view/login/auth.dart

Feat: Better error handling in loading screen

---

app/assets/startup.svg
app/lib/client/client_submodules/substitutions.dart
app/lib/l10n/app_de.arb
app/lib/l10n/app_en.arb
app/lib/startup.dart
app/pubspec.yaml

Startup cleanup

---

app/lib/client/client.dart
app/lib/client/client_submodules/calendar.dart
app/lib/client/client_submodules/conversations.dart
app/lib/client/connection_checker.dart
app/lib/client/fetcher.dart
app/lib/home_page.dart
app/pubspec.yaml

fixes #212 
may addresses #221 
Custom connection checker using already sent requests and proper low-bandwidth endpoints instead of multiple requests.

optimize network usage with custom network checking implementation

---

app/android/app/build.gradle
app/android/app/proguard-rules.pro
app/lib/client/client_submodules/mein_unterricht.dart
app/lib/shared/widgets/whats_new.dart
app/lib/view/substitutions/chips_input.dart
app/lib/view/substitutions/filtersettings.dart

fix: unable to create filters on some devices

---

app/lib/l10n/app_de.arb
app/lib/l10n/app_en.arb
app/lib/view/timetable/view.dart

Adds Tooltips on the Timetable for the Refresh button and the new Personal/Class Toggle button

Add Tooltips for Timetable Buttons

---

app/lib/client/client.dart
app/lib/client/storage.dart
app/lib/main.dart
app/lib/view/settings/subsettings/theme_changer.dart
app/template_config.json

Fix  #264
How?
Copy `template_config.json` and put it somewhere safe, or not. Adjust it and attach `--dart-define-from-file=PATH_TO_YOUR_COPY` to your run args.
Example:
`--debug --dart-define ID="6091"`, quotation marks are optional. I guess you could use $ENV_STUFF here.
For other arguments see `template_config.json`.
You can provide a file and later disable it with the argument  `--dart-define DISABLE_OVERWRITE=true`

Configure settings through environment variables.

---

app/lib/client/client_submodules/timetable.dart
app/lib/main.dart
app/lib/shared/types/fach.dart
app/lib/view/timetable/view.dart
app/pubspec.yaml

fix: timetable

---

app/android/build.gradle
app/lib/main.dart
app/pubspec.yaml

fix: Proxy on iOS devices

---

app/lib/view/mein_unterricht/homework_box.dart

Fixes the overflow of the homework box when screen rotates

fix: Homework box

---

app/lib/client/client.dart
app/lib/client/connection_checker.dart
app/lib/client/cryptor.dart
app/lib/l10n/app_de.arb
app/lib/l10n/app_en.arb
app/lib/shared/exceptions/client_status_exceptions.dart
app/lib/shared/widgets/error_view.dart
app/lib/startup.dart

Closes #258 
If the server returns code 503 the app will show that Lanis is down. This doesn't include timeout because these could also be client side.
Demo:
https://github.com/user-attachments/assets/f68f9c90-7d10-4c51-a3ff-d47495765866

Add own error message if lanis is down

---

app/lib/main.dart
app/lib/view/timetable/view.dart
app/pubspec.yaml

This PR introduces localization support for the SfCalendar widget and configures the "week" view to start on Monday by default.
Monday is chosen as the default start day, as it's generally preferred over Sunday; however, this setting could theoretically be adjusted based on the selected language (though this functionality is not implemented in this PR).
This implementation uses the official syncfusion_localizations library (https://pub.dev/packages/syncfusion_localizations). Please note that syncfusion_localizations follows a proprietary licensing model. Since syncfusion_flutter_calendar operates under the same licensing terms, I assume you hold the appropriate license needed to merge this PR.
Additionally, any other modified sections in the file are due to automatic formatting, which …

Localization Timetable

---

app/lib/applets/data_storage/data_storage_root_view.dart
app/lib/applets/data_storage/node_view.dart
app/lib/applets/timetable/student/student_timetable_view.dart
app/lib/home_page.dart
app/lib/l10n/app_de.arb
app/lib/l10n/app_en.arb
app/lib/startup.dart
app/lib/themes.dart
app/lib/view/login/school_selector.dart

Some UX Improvements.
Fixes Amoled background for timetable header
Shows the current week number instead of month and year in the timetable header
Translates Datastorage (Errors and Title)
Fixes spelling of iOS & iPadOS (Ios → iOS & IpadOS → iPadOS)
Stops annoying user for notifications if permanently disabled.
Closes #313
Closes #306

Fixes and small UX improvements

---

app/lib/applets/calendar/calendar_view.dart
app/lib/widgets/offline_available_applets_section.dart

Missing padding in offline selection

---

app/lib/applets/lessons/student/course_overview.dart
app/lib/applets/lessons/student/parser.dart
app/lib/l10n/app_de.arb
app/lib/l10n/app_en.arb

This PR fixes the parsing of comments on Grades (student side) and also improves the view of comments by clearly marking them as comments.

Fix & Improve comments on grades / marks

---

app/lib/core/database/account_database/account_db.dart
app/lib/core/sph/session.dart
app/lib/home_page.dart
app/lib/l10n/app_de.arb
app/lib/l10n/app_en.arb
app/lib/startup.dart
app/lib/view/login/auth.dart
app/lib/widgets/reset_account_page.dart

Account recovery on server side password change/account deletion

---

app/lib/applets/calendar/calendar_view.dart
app/lib/applets/calendar/parser.dart
app/lib/models/calendar_event.dart

Adds a request, to load the categories, but it is way more detailed in this way. Also people who know the lanis-theme can adapt fast.

Calendar colors

---

app/lib/applets/study_groups/student/parser.dart

fixes bug when next label

---

app/lib/applets/data_storage/file_listtile.dart
app/lib/applets/lessons/student/course_overview.dart
app/lib/utils/file_operations.dart
app/lib/utils/logger.dart
app/lib/view/settings/subsettings/about.dart
app/lib/view/settings/subsettings/debug_export.dart
app/pubspec.yaml

feat: add debug export functionality and enhance file handling 

---

lib/applets/lessons/student/background.dart

feat: add background task for notifying students about new homework
