app/lib/client/client.dart
Hier wurde einfach nur vergessen `i=$schoolID` einzugeben.
Jetzt wird auch beim Drawer die richtige Schule angezeigt.
=> 🐛 getSchoolInfo() holt nur Daten von Schule 5182

app/lib/client/client.dart, app/lib/client/cryptor.dart
Sollte jetzt "funktionieren". Hat eigentlich schon immer funktioniert, man musste nur mit UTF8 kodieren nicht BASE64, ja super.
+ funktionierendes decryptString hinzugefügt.
+ Login Verschlüsselungs fix von @alessioC42 vom `mein_unterricht` branch.
+ decrypt() und decryptString() kann auch `null` returnen.
=> Fix encryption support

app/lib/client/client.dart, app/lib/client/cryptor.dart, app/lib/main.dart, app/lib/view/conversations/conversations.dart, app/lib/view/conversations/detailed_conversation.dart, app/lib/view/settings/subsettings/supported_features.dart, app/pubspec.lock, app/pubspec.yaml
**Erst ready zu mergen, wenn die Punkte fertig sind:**
*Aktuelles Layout*
*Man kann eingeblendete und ausgeblendete Unterhaltungen sehen.*
*Ungelesene Unterhaltung*
*Error Page*
*Finales Layout*
*Klickbarer Link (und Email) mit flutter_linkify*
*Bug*
*Manchmal haben Nachrichten keinen Benutzernamen (Sie werden nur als " , " angezeigt).*
Neue Nachrichten zu erstellen und so würde ich auf ein anderen Pull Request verschieben.
Das gleiche mit Push Benachrichtigungen und filter.
=> Support für "Nachrichten Beta-Version" hinzufügen

app/lib/client/client.dart, app/lib/client/storage.dart, app/lib/main.dart, app/lib/view/conversations/conversations.dart, app/lib/view/mein_unterricht/course_overview.dart, app/lib/view/mein_unterricht/mein_unterricht.dart, app/lib/view/settings/subsettings/notifications.dart, app/lib/view/settings/subsettings/send_bugreport.dart, app/lib/view/settings/subsettings/theme_changer.dart, app/pubspec.lock, app/pubspec.yaml
Implementing shared_preferences for non-encrypted storage can boost performance, as the data does not need to be encrypted or decrypted for non-sensitive data anymore.
=> Storage improvement

app/lib/main.dart, app/lib/view/conversations/conversations.dart, app/lib/view/mein_unterricht/mein_unterricht.dart
Es ist jetzt so, dass es standartmäßig die vier einträge
- vertretungsplan
- kalender
- nachrichten
- mein unterricht
gibt. Was nicht unterstützt wird, wird aus der Navigationbar konmplett gestrichen. 
Die Navigationbar in "Mein Unterricht" (main page) wurde durch eine TabView ausgetauscht.
=> Bottom navbar

app/lib/main.dart
Die App crasht, wenn sie von einer Schule (hier 5170) ohne das Vertretungsplan Modul verwendet wird. 
Dies liegt daran, dass der Vertretungsplan als default ausgewählt ist, selbst wenn er nicht unterstützt wird.
=> Fix substitutions not supported

app/lib/main.dart, app/pubspec.lock, app/pubspec.yaml
Zeigt ein Error Widget bei Fehlern, die (hauptsächlich) nicht durch den Parser oder Fetcher ausgelöst werden. Somit gibt es auch keinen grauen Screen mehr.
[Screencast from 2023-12-22 18-39-50.webm](https://github.com/alessioC42/lanis-mobile/assets/73837560/83867c06-d4a1-4480-819e-1cf79c4b0fb3)
=> Add error widget on unexpected errors

app/lib/client/client.dart, app/lib/view/settings/subsettings/supported_features.dart
In client und supported_features ist eine Liste von Modulen enthalten, die case-sensitive auf matches überprüft wird.
Dieser PR ändert sämtliche solchen Listen in vollständige Kleinschreibung und überprüft auch nur dagegen. So können Dopplungen mit unterschiedlichen Cases entfernt werden und ähnlichen Fehlern vorgebeugt werden.
=> Groß-/Kleinschreibung in der Erkennung von Modulen nicht beachten.

app/lib/client/client.dart, app/lib/main.dart, app/lib/shared/apps.dart, app/lib/view/bug_report/send_bugreport.dart, app/lib/view/login/setup_screen_page_view_models.dart, app/lib/view/settings/settings.dart, app/lib/view/settings/subsettings/supported_features.dart
Um Redundanz zu vermeiden und damit zukünftige Fehler, werden die Namen der Module zur Überprüfung ihrer Unterstützung in einem Enum aufgelistet. Dies führt vor allem dazu, dass die Liste unterstützter Module immer automatisch mit der tatsächlichen Unterstützung übereinstimmt, selbst wenn nur der Name geändert wird.
=> Modul-Bezeichnungen als Enum implementieren

app/lib/shared/marquee.dart, app/lib/view/vertretungsplan/substitutionWidget.dart
Hier wird das Substitutionswidget so angepasst, dass es mit längeren Titeln wie in #136 zurechtkommt. Dazu werden Scroller verwendet. 
Jetzt sind auch die Hinweise in der gleichen Zeile wie das Icon.
Bei der Einführung der Laufschrift wurde eine schöne Animation erstellt, die ich beibehalten würde:
https://github.com/alessioC42/lanis-mobile/assets/84250128/075ea33a-ed86-4424-8447-1e502ec86b7f
closes #136
=> Modify substitutions widget to enable overflow title

app/lib/client/client.dart, app/lib/client/cryptor.dart, app/lib/view/calendar/calendar.dart, app/lib/view/login/auth.dart, app/lib/view/login/screen.dart
Einige reguläre Ausdrücke sind nicht optimal formuliert oder es wird RegExp verwendet, an Stellen, an denen es nicht notwendig ist.
=> Reguläre Ausdrücke optimieren

app/lib/view/vertretungsplan/filterlogic.dart, app/lib/view/vertretungsplan/filtersettings.dart
Bisher muss man Regex schreiben um die Filter zu benutzen.
Fügt die Möglichkeit hinzu auch mit durch Semikolons getrennte Listen zu filtern.
=> Vertretungsplan Filter nach Semikolon-Liste

app/lib/client/client_submodules/mein_unterricht.dart, app/pubspec.yaml
Due to (what I think is) a change in the interface of "My Lessons" in the SPH web interface, the Exam section was not displayed correctly in the Application. I think I fixed it, but I cannot test it because none of my courses use the Exam section. @kurwjan, if I remember correctly you had something in there?
=> fix: exams not rendered due to change in Lanis Layout

app/android/app/src/main/AndroidManifest.xml, app/android/app/src/main/res/xml/locales_config.xml, app/android/build.gradle, app/android/gradle.properties, app/android/gradle/wrapper/gradle-wrapper.properties, app/android/settings.gradle, app/lib/l10n/app_de.arb, app/lib/l10n/app_en.arb, app/lib/view/settings/settings.dart, app/pubspec.yaml
Android 13 Introduced [Per-app language preferences](https://developer.android.com/guide/topics/resources/app-languages)  that allow the user to pick a locale for a specific app regardless of system language. This would be a solution for a locale picker (at least on Android 13+) for older version there would be the need for a in app locale picker but this can be added later and a In-App and Android Settings locale picker should work at the same time according to Android Developers so #213 will not be closed.
Demo (ignore that the last one is only half visible that is a bug in OneUI that also happens to other Apps):
https://github.com/user-attachments/assets/9e4eb5f5-8d62-4ebb-91e0-51c3f4559074
=> Added Per-App Language functionality (for Language Picker via Android Settings)

README.md
The App is in the App Store and was tested by more Schools than listed (including my own). So this section is no longer needed.
=> Removed .ipa section in README.md

app/lib/l10n/app_en.arb
Randomly noticed on the Startup Screen when starting the app that instead of `customize` there was `custumize` Fixed it here
=> Fixed typo on Startup Screen

app/pubspec.yaml
Fails in `release mode` to build and logs something like this: `"AAPT: error: resource android:attr/lStar not found."`
Related issue: https://github.com/flutter/flutter/issues/153281
Fork from @Rajala1404: https://github.com/Rajala1404/http_proxy
=> Replace http_proxy with a fork which supports v3.24.x

app/android/app/build.gradle, app/android/app/src/main/AndroidManifest.xml, app/android/app/src/main/res/values-night-v31/styles.xml, app/android/app/src/main/res/values-night/styles.xml, app/android/app/src/main/res/values-v31/styles.xml, app/android/app/src/main/res/values/styles.xml, app/lib/client/client.dart, app/lib/home_page.dart, app/lib/l10n/app_de.arb, app/lib/l10n/app_en.arb, app/lib/shared/launch_file.dart, app/lib/shared/widgets/error_view.dart, app/lib/view/moodle.dart, app/pubspec.yaml
Adding a WebView for Moodle (aka a minimal restricted browser?) instead of redirecting to the login website.
We need to use the `flutter_inappwebview` package because Lanis is buggy with the official WebView package and we have more options. 
iOS also shouldn't be a hassle, there are more infos in the [docs](https://inappwebview.dev/docs/intro#setup-ios). (normally it should work without editing configs)
Issues:
- ~Currently doesn't use Material 3 Components, instead I get M2 components although I specified M3.~ Uses a mix of M2 and M3, sometimes weird colour choices but it isn't an issue.
- Need to switch `flutter_inappwebview` with `webview_inapp` temporarily because it doesn't build in release mode.
Todos:
- ~for iOS the URL scheme `moodlemobile` must be allowed, more info …
=> Add moodle webview

app/lib/client/client_submodules/calendar.dart, app/lib/client/fetcher.dart, app/lib/shared/keyboard_observer.dart, app/lib/shared/types/calendar_event.dart, app/lib/view/calendar/calendar.dart, app/lib/view/data_storage/root_view.dart, app/lib/view/timetable/view.dart
Implementing on device search for the calendar. (network search is scuffed, only returns specific results)
Also: allowing classic timetable view alongside Day view.
=> calendar: add search and data class + cleanup

SECURITY.md
The Privacy Policy still contained that there are Analytics that are needed to develop the app. I think that are still ledtovers from countly because as far as i know we dont collect any Telemetry/Analytics
=> Remove analytics leftover in SECURITY.md

app/lib/view/timetable/view.dart
This pull request addresses the issue where clicking on an appointment displays a popup for a different appointment. The problem was caused by incorrect ID generation in the TimeTableDataSource class. The ID generation logic has been corrected to ensure each appointment has a unique ID based on the dayIndex and lessonIndex.
Before:
After:
=> Fix appointment popup mismatch by correcting ID generation

app/lib/applets/substitutions/substitutions_view.dart
This pull request fixes the bug where the 'More Information' dialog appears in the substitutions without any content.
=> Fix: More information button now hides without content. 

app/lib/applets/substitutions/substitutions_view.dart
With the introduction of information for a substitution day, it became common to have a tab without any substitutions.
To make it clearer that there are no substitutions, I have completely removed the badge when there is no substitution, making it more noticeable to the user.
This is just an idea:
=> Remove badge when no substitutions

app/lib/applets/calendar/calendar_view.dart
About issue #370 
This pull request includes a visual enhancement to the calendar view in the `app/lib/applets/calendar/calendar_view.dart` file. The change adds a border to the event indicators to improve their visibility.
Visual enhancement to calendar view:
* [`app/lib/applets/calendar/calendar_view.dart`](diffhunk://#diff-6d735357f855d2a5e11a8c31df4936de614fc7bf2ee4603fb67741b49ff63f6cL514-R515): Added a border to the event indicators with a color from the theme's color scheme and a width of 0.7.
Border with both other colors and black
=> add border to calender event indicators

app/lib/applets/substitutions/substitutions_listtile.dart
This pull request includes changes to the `SubstitutionListTile` class in `app/lib/applets/substitutions/substitutions_listtile.dart` to improve the layout and ensure better handling of long text.
Improvements to layout and text handling:
* [`app/lib/applets/substitutions/substitutions_listtile.dart`](diffhunk://#diff-a47cfa5e2ee0aeb0f336ddc3792a8d37f9a328780a84b3e1f2a3327cc64bc23bR43-R46): Added a `LayoutBuilder` to limit the class width to 30% of the tile width.
* [`app/lib/applets/substitutions/substitutions_listtile.dart`](diffhunk://#diff-a47cfa5e2ee0aeb0f336ddc3792a8d37f9a328780a84b3e1f2a3327cc64bc23bL121-R134): Replaced `SizedBox` with `ConstrainedBox` to apply the width constraint and added a `MarqueeWidget` to handle horizontal scrolling of long text with ellipsis overflow. …
=> Prevent classes in substitution tiles from overflowing

app/lib/core/sph/session.dart
Every hot restart triggers a request being logged. Looking at today's logs, you can see a school's count is higher than yesterday's at around 06:00, likely due to hot restarts or  generally development launches.  This skews the stats for the schools we are working on. Not trivial though
=> only log in release mode

app/lib/applets/substitutions/parser.dart, app/lib/applets/substitutions/substitutions_view.dart, app/lib/l10n/intl_de.arb, app/lib/l10n/intl_en.arb, app/lib/models/substitution.dart
This pull request fixes the issue where the substitution page displays only the current time instead of the edited time from lanis.
=> Fix: Show actual update time for substitutions

app/android/app/src/main/AndroidManifest.xml, app/android/build.gradle, app/pubspec.yaml
Fixes android build crash by #385 . Idk, probably we should ditch that plugin anyways, but iOS works, and working things do not get removed ig. But yeah, that fixes the android build thinggy.
And upgraded version. Idk why it was old - like very old. @alessioC42 Hope this does not break iOS, as it is the backgroundfetcher for it
=> fix crash introduced by PR

app/lib/core/sph/session.dart, app/pubspec.yaml
Fixes #339.
This escapes all symbols on an app layer, as it seems like they are unescaped at many places. It does not really hurt performance:
```
I/flutter ( 5170): Response Size: 743
I/flutter ( 5170): Took to unescape: 47μs
I/flutter ( 5170): Response Size: 375251
I/flutter ( 5170): Took to unescape: 1697μs
I/flutter ( 5170): Response Size: 50979
I/flutter ( 5170): Took to unescape: 6332μs
```
In my tests the biggest time I have encountered is 8ms for e.g. my substitutions (which you know are pretty big). So there should be little to no difference.
In theory unescaping could break JSON payloads though, so this would need testing, but all functions that are available to me work.
=> fixes escaping

app/lib/applets/lessons/student/parser.dart
SPH changed the big to an td so parsing of topic titles was broken.
Closes #414
=> Fixes parsing of topic titles in the history view of a lesson

app/devtools_options.yaml, app/lib/core/database/account_database/account_db.dart, app/lib/main.dart
Due to the switch of apple developer accounts the keychain is unavoidable lost. Therefore all users have to be logged out of the old version.
=> Implement account deletion and add devtools options configuration

app/android/app/build.gradle, app/pubspec.yaml
Excludes GMS and datatransport. 
Also completely removes the Android project from flutter_doc_scanner (to prevent MLKit from being depended on).
Closes #426
=> Exclude Google Spyware from Android Build
